name: Delete Old Workflow Runs

on:
  workflow_dispatch: # 웹에서 수동으로 'Run workflow' 버튼을 눌러 실행
  schedule:
    - cron: '0 0 * * 0' # 매주 일요일 자정에 자동 실행

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0          # 0으로 설정 시 지정된 개수 제외하고 모두 삭제
          keep_minimum_runs: 0    # 최신 기록을 몇 개 남길지 설정 (예: 0개 또는 3개)
