name: Delete Workflow Runs

on:
  workflow_dispatch: # Actions 탭에서 수동으로 'Run workflow' 버튼을 눌러 실행

permissions:
  actions: write # 권한 에러 해결을 위해 추가된 필수 설정
  contents: read

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0          # 0으로 설정 시 조건에 따라 전체 삭제
          keep_minimum_runs: 0    # 남겨둘 최신 실행 기록 개수 (필요에 따라 수정 가능)
